### ISSUE TITLE
rename to 'spf'?

### ISSUE THREAD

**Issue by porjo** [eaigner/libspf2#3]
It'd be nice to rename the package to `spf` in keeping with Go's philosophy of brevity and simplicity.

**Comment by eaigner** [comment]
I don't want to hide the fact that this is a `libspf2` wrapper, that's why it is called `libspf2`. Also it's not more Go-like to just shorten the package, Go itself has some pretty verbose names in its standard lib (e.g. `quotedprintable`)

**Comment by porjo** [comment]
It seems clear you've made up your mind, but for what it's worth:

> I don't want to hide the fact that this is a libspf2 wrapper

I'm not suggesting it be hidden. The package doco should definitely mention this fact, but not necessary in the package name. I can think of many Go packages that wrap C libraries which don't mirror the C library name.

> Also it's not more Go-like to just shorten the package

Go does encourage brevity where that makes sense. [Effective Go](https://golang.org/doc/effective_go.html#names) says about package names: `Err on the side of brevity, since everyone using your package will be typing that name`. In my opinion, this is a good example. The `lib` prefix is redundant.

**Comment by eaigner** [comment]
I don't see what the problem is. You can always import it as `spf` with

```
import spf "github.com/eaigner/libspf2"
```

if you like that better
